{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Reovcation Service API",
    "description" : "Revocation Service API",
    "contact" : {
      "name" : "eclipse-tractusx",
      "url" : "https://projects.eclipse.org/projects/automotive.tractusx",
      "email" : "tractusx-dev@eclipse.org"
    },
    "version" : "0.0.1"
  },
  "servers" : [
    {
      "url" : "http://localhost:8081",
      "description" : "Generated server url"
    }
  ],
  "security" : [
    {
      "Authenticate using access_token" : []
    }
  ],
  "tags" : [
    {
      "name" : "Revocation Service",
      "description" : "Revocation Service API"
    }
  ],
  "paths" : {
    "/api/v1/revocations/verify" : {
      "post" : {
        "tags" : [
          "Revocation Service"
        ],
        "summary" : "Verify Revocation status",
        "description" : "Verify revocation status of Credential",
        "operationId" : "verifyRevocation",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/CredentialStatusDto"
              },
              "example" : {
                "id" : "https://977d-203-129-213-107.ngrok-free.app/api/v1/revocations/credentials/BPNL000000000000/revocation/1#12",
                "statusPurpose" : "revocation",
                "statusListIndex" : "12",
                "statusListCredential" : "https://977d-203-129-213-107.ngrok-free.app/api/v1/revocations/credentials/BPNL000000000000/revocation/1",
                "type" : "StatusList2021"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Status of credential",
            "content" : {
              "application/json" : {
                "examples" : {
                  "if credential is revoked" : {
                    "description" : "if credential is revoked",
                    "value" : {
                      "status" : "revoked"
                    }
                  },
                  "if credential is active" : {
                    "description" : "if credential is is active",
                    "value" : {
                      "status" : "active"
                    }
                  }
                }
              }
            }
          },
          "403" : {
            "description" : "ForbiddenException: invalid caller"
          },
          "401" : {
            "description" : "UnauthorizedException: invalid token"
          },
          "500" : {
            "description" : "RevocationServiceException: Internal Server Error"
          }
        }
      }
    },
    "/api/v1/revocations/status-entry" : {
      "post" : {
        "tags" : [
          "Revocation Service"
        ],
        "summary" : "Create or Update a Status List Credential",
        "description" : "Create the status list credential if it does not exist, else update it.",
        "operationId" : "createStatusListVC",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/StatusEntryDto"
              },
              "example" : {
                "purpose" : "revocation",
                "issuerId" : "did:web:localhost:BPNL000000000000"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "403" : {
            "description" : "ForbiddenException: invalid caller"
          },
          "200" : {
            "description" : "Status list credential created/updated successfully.",
            "content" : {
              "application/json" : {
                "example" : {
                  "id" : "https://977d-203-129-213-107.ngrok-free.app/api/v1/revocations/credentials/BPNL000000000000/revocation/1#17",
                  "statusPurpose" : "revocation",
                  "statusListIndex" : "17",
                  "statusListCredential" : "https://977d-203-129-213-107.ngrok-free.app/api/v1/revocations/credentials/BPNL000000000000/revocation/1",
                  "type" : "StatusList2021"
                }
              }
            }
          },
          "401" : {
            "description" : "UnauthorizedException: invalid token"
          },
          "500" : {
            "description" : "RevocationServiceException: Internal Server Error"
          }
        }
      }
    },
    "/api/v1/revocations/revoke" : {
      "post" : {
        "tags" : [
          "Revocation Service"
        ],
        "summary" : "Revoke a VerifiableCredential",
        "description" : "Revoke a VerifiableCredential using the provided Credential Status",
        "operationId" : "revokeCredential",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/CredentialStatusDto"
              },
              "example" : {
                "id" : "https://977d-203-129-213-107.ngrok-free.app/api/v1/revocations/credentials/BPNL000000000000/revocation/1#12",
                "statusPurpose" : "revocation",
                "statusListIndex" : "12",
                "statusListCredential" : "https://977d-203-129-213-107.ngrok-free.app/api/v1/revocations/credentials/BPNL000000000000/revocation/1",
                "type" : "StatusList2021"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "403" : {
            "description" : "ForbiddenException: invalid caller"
          },
          "409" : {
            "description" : "ConflictException: Revocation service error",
            "content" : {
              "application/json" : {
                "example" : {
                  "type" : "StatusList2021",
                  "title" : "Revocation service error",
                  "status" : "409",
                  "detail" : "Credential already revoked",
                  "instance" : "/api/v1/revocations/revoke",
                  "timestamp" : 1707133388128
                }
              }
            }
          },
          "401" : {
            "description" : "UnauthorizedException: invalid token"
          },
          "200" : {
            "description" : "Verifiable credential revoked successfully."
          },
          "500" : {
            "description" : "RevocationServiceException: Internal Server Error"
          }
        }
      }
    },
    "/api/v1/revocations/credentials/{issuerBPN}/{status}/{index}" : {
      "get" : {
        "tags" : [
          "Revocation Service"
        ],
        "summary" : "Get status list credential",
        "description" : "Get status list credential using the provided issuer BPN and status purpose and status list index",
        "operationId" : "getStatusListCredential",
        "parameters" : [
          {
            "name" : "issuerBPN",
            "in" : "path",
            "description" : "Issuer BPN",
            "required" : true,
            "schema" : {
              "type" : "string"
            },
            "example" : "BPNL000000000000"
          },
          {
            "name" : "status",
            "in" : "path",
            "description" : "Status Purpose ( Revocation or Suspension)",
            "required" : true,
            "schema" : {
              "type" : "string"
            },
            "example" : "revocation"
          },
          {
            "name" : "index",
            "in" : "path",
            "description" : "status list index",
            "required" : true,
            "schema" : {
              "type" : "string"
            },
            "example" : 1
          }
        ],
        "responses" : {
          "200" : {
            "description" : "Get Status list credential ",
            "content" : {
              "application/json" : {
                "example" : {
                  "@context" : [
                    "https://www.w3.org/2018/credentials/v1",
                    "https://w3id.org/vc/status-list/2021/v1",
                    "https://w3id.org/security/suites/jws-2020/v1"
                  ],
                  "id" : "http://localhost/api/v1/revocations/credentials/BPNL000000000000/revocation/1",
                  "type" : [
                    "VerifiableCredential",
                    "StatusList2021Credential"
                  ],
                  "issuer" : "did:web:localhost:BPNL000000000000",
                  "issuanceDate" : "2024-02-05T09:39:58Z",
                  "credentialSubject" : [
                    {
                      "statusPurpose" : "revocation",
                      "id" : "http://localhost/api/v1/revocations/credentials/BPNL000000000000/revocation/1",
                      "type" : "StatusList2021",
                      "encodedList" : "H4sIAAAAAAAA/wMAAAAAAAAAAAA="
                    }
                  ],
                  "proof" : {
                    "proofPurpose" : "assertionMethod",
                    "type" : "JsonWebSignature2020",
                    "verificationMethod" : "did:web:localhost:BPNL000000000000#ed463e4c-b900-481a-b5d0-9ae439c434ae",
                    "created" : "2024-02-05T09:39:58Z",
                    "jws" : "eyJhbGciOiJFZERTQSJ9..swX1PLJkSlxB6JMmY4a2uUzR-uszlyLrVdNppoYSx4PTV1LzQrDb0afzp_dvTNUWEYDI57a8iPh78BDjqMjSDQ"
                  }
                }
              }
            }
          },
          "404" : {
            "description" : "Status list credential not found"
          },
          "500" : {
            "description" : "RevocationServiceException: Internal Server Error"
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "CredentialStatusDto" : {
        "required" : [
          "id",
          "statusListCredential",
          "statusListIndex",
          "statusPurpose",
          "type"
        ],
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string"
          },
          "statusPurpose" : {
            "type" : "string"
          },
          "statusListIndex" : {
            "type" : "string"
          },
          "statusListCredential" : {
            "type" : "string"
          },
          "type" : {
            "type" : "string"
          }
        }
      },
      "StatusEntryDto" : {
        "required" : [
          "issuerId",
          "purpose"
        ],
        "type" : "object",
        "properties" : {
          "purpose" : {
            "type" : "string"
          },
          "issuerId" : {
            "type" : "string"
          }
        }
      }
    },
    "securitySchemes" : {
      "Authenticate using access_token" : {
        "type" : "apiKey",
        "description" : "**Bearer (apiKey)**\nJWT Authorization header using the Bearer scheme.\nEnter **Bearer** [space] and then your token in the text input below.\nExample: Bearer 12345abcdef",
        "name" : "Authorization",
        "in" : "header"
      }
    }
  }
}
